// Seed Data for Project Lunayve Construction HRMS
export const initialDepartments = [
  { id: 'dept-1', code: 'EXEC', name: 'Executive & Management', description: 'Corporate officers and executive team', is_active: true },
  { id: 'dept-2', code: 'HR', name: 'Human Resources', description: 'Talent, payroll, relations, and labor compliance', is_active: true },
  { id: 'dept-3', code: 'FIN', name: 'Finance & Accounting', description: 'Financial planning, accounting, and disbursements', is_active: true },
  { id: 'dept-4', code: 'ENG', name: 'Engineering & Architecture', description: 'Structural, civil, MEP engineering and design', is_active: true },
  { id: 'dept-5', code: 'OPS', name: 'Construction Operations', description: 'Site execution, superintendents, and workforce crews', is_active: true },
  { id: 'dept-6', code: 'HSE', name: 'Safety & HSE', description: 'Health, safety, environment and DOLE OSH compliance', is_active: true },
  { id: 'dept-7', code: 'PROC', name: 'Procurement & Logistics', description: 'Material sourcing, heavy equipment, and warehousing', is_active: true },
  { id: 'dept-8', code: 'QAQC', name: 'Quality Assurance & QC', description: 'Standards testing, inspection, and material compliance', is_active: true }
];

export const initialDesignations = [
  // Office / Professional
  { id: 'desig-1', code: 'PM', title: 'Project Manager', workforce_category: 'office', department_id: 'dept-4', is_active: true },
  { id: 'desig-2', code: 'SR_CE', title: 'Senior Civil Engineer', workforce_category: 'office', department_id: 'dept-4', is_active: true },
  { id: 'desig-3', code: 'STRUCT_ENG', title: 'Structural Engineer', workforce_category: 'office', department_id: 'dept-4', is_active: true },
  { id: 'desig-4', code: 'ARCH', title: 'Senior Architect', workforce_category: 'office', department_id: 'dept-4', is_active: true },
  { id: 'desig-5', code: 'HR_MGR', title: 'HR Manager', workforce_category: 'office', department_id: 'dept-2', is_active: true },
  { id: 'desig-6', code: 'HR_OFFICER', title: 'HR & Labor Relations Officer', workforce_category: 'office', department_id: 'dept-2', is_active: true },
  { id: 'desig-7', code: 'PAYROLL_SPEC', title: 'Payroll Specialist', workforce_category: 'office', department_id: 'dept-3', is_active: true },
  { id: 'desig-8', code: 'SR_ACCT', title: 'Senior Accountant', workforce_category: 'office', department_id: 'dept-3', is_active: true },
  { id: 'desig-9', code: 'SAFETY_OFF', title: 'Safety Officer (SO3/SO4)', workforce_category: 'office', department_id: 'dept-6', is_active: true },
  { id: 'desig-10', code: 'QS_ENG', title: 'Quantity Surveyor (QS)', workforce_category: 'office', department_id: 'dept-4', is_active: true },
  { id: 'desig-11', code: 'DOC_CTRL', title: 'Document Controller', workforce_category: 'office', department_id: 'dept-2', is_active: true },
  
  // Site / Skilled Construction Workers
  { id: 'desig-12', code: 'GEN_FOREMAN', title: 'General Site Foreman', workforce_category: 'site', department_id: 'dept-5', is_active: true },
  { id: 'desig-13', code: 'SITE_SUP', title: 'Site Supervisor', workforce_category: 'site', department_id: 'dept-5', is_active: true },
  { id: 'desig-14', code: 'CARP_LEAD', title: 'Master Carpenter / Lead', workforce_category: 'site', department_id: 'dept-5', is_active: true },
  { id: 'desig-15', code: 'CARP', title: 'Formwork Carpenter', workforce_category: 'site', department_id: 'dept-5', is_active: true },
  { id: 'desig-16', code: 'MASON_LEAD', title: 'Master Mason', workforce_category: 'site', department_id: 'dept-5', is_active: true },
  { id: 'desig-17', code: 'MASON', title: 'Finishing Mason', workforce_category: 'site', department_id: 'dept-5', is_active: true },
  { id: 'desig-18', code: 'ELEC_MASTER', title: 'Master Electrician', workforce_category: 'site', department_id: 'dept-5', is_active: true },
  { id: 'desig-19', code: 'ELEC', title: 'Construction Electrician', workforce_category: 'site', department_id: 'dept-5', is_active: true },
  { id: 'desig-20', code: 'PLUMB', title: 'Master Plumber / Pipefitter', workforce_category: 'site', department_id: 'dept-5', is_active: true },
  { id: 'desig-21', code: 'WELD_SMAW', title: 'SMAW/GTAW Certified Welder', workforce_category: 'site', department_id: 'dept-5', is_active: true },
  { id: 'desig-22', code: 'STEELMAN', title: 'Rebar Steelman', workforce_category: 'site', department_id: 'dept-5', is_active: true },
  { id: 'desig-23', code: 'EQ_OP_TOWER', title: 'Tower Crane Operator', workforce_category: 'site', department_id: 'dept-5', is_active: true },
  { id: 'desig-24', code: 'EQ_OP_EXC', title: 'Excavator & Heavy Eq Operator', workforce_category: 'site', department_id: 'dept-5', is_active: true },
  { id: 'desig-25', code: 'RIGGER', title: 'Certified Heavy Rigger', workforce_category: 'site', department_id: 'dept-5', is_active: true },
  { id: 'desig-26', code: 'LABOR_SKILLED', title: 'Skilled Construction Laborer', workforce_category: 'site', department_id: 'dept-5', is_active: true },
  { id: 'desig-27', code: 'LABOR_GEN', title: 'General Site Laborer', workforce_category: 'site', department_id: 'dept-5', is_active: true }
];

export const initialProjects = [
  {
    id: 'prj-1',
    project_code: 'PRJ-2026-ALPHA',
    name: 'Lunayve Tower Alpha',
    client: 'Megaworld Prime Holdings',
    location: 'Emerald Ave., Ortigas Center, Pasig City',
    project_manager_name: 'Engr. Bernardo Alcantara',
    project_manager_id: 'emp-1',
    start_date: '2025-06-01',
    end_date: '2027-12-31',
    estimated_budget: 450000000.00,
    status: 'Active',
    description: '45-Storey Grade-A Commercial and Smart Office High-Rise Tower with 5-level basement parking.'
  },
  {
    id: 'prj-2',
    project_code: 'PRJ-2026-BAY',
    name: 'Bay Horizon Residences',
    client: 'Anchor Land Development',
    location: 'Aseana Business Park, Parañaque City',
    project_manager_name: 'Arch. Christine Reyes',
    project_manager_id: 'emp-3',
    start_date: '2025-09-15',
    end_date: '2028-03-30',
    estimated_budget: 680000000.00,
    status: 'Active',
    description: 'Triple-tower luxury residential seaside condominium with resort-style podium amenities.'
  },
  {
    id: 'prj-3',
    project_code: 'PRJ-2026-HUB',
    name: 'Lunayve East Logistics Hub',
    client: 'Eastern Express Logistics Inc.',
    location: 'Felix Ave., Cainta, Rizal',
    project_manager_name: 'Engr. Daniel Villanueva',
    project_manager_id: 'emp-4',
    start_date: '2026-01-10',
    end_date: '2026-11-20',
    estimated_budget: 185000000.00,
    status: 'Active',
    description: '120,000 sqm high-clearance smart distribution logistics facility and cold storage center.'
  }
];

export const initialSites = [
  {
    id: 'site-1',
    site_code: 'SITE-ALPHA-01',
    name: 'Tower Alpha - Substructure & Basements',
    project_id: 'prj-1',
    location: 'Zone A - Excavation & Mat Foundation, Ortigas',
    site_supervisor_name: 'Rolando Mendoza',
    foreman_name: 'Danilo Cruz',
    start_date: '2025-06-01',
    end_date: '2026-06-30',
    status: 'Active'
  },
  {
    id: 'site-2',
    site_code: 'SITE-ALPHA-02',
    name: 'Tower Alpha - Superstructure & Core',
    project_id: 'prj-1',
    location: 'Zone B - Shear Wall & Concrete Decking, Ortigas',
    site_supervisor_name: 'Rolando Mendoza',
    foreman_name: 'Arturo Santos',
    start_date: '2026-02-01',
    end_date: '2027-10-15',
    status: 'Active'
  },
  {
    id: 'site-3',
    site_code: 'SITE-BAY-01',
    name: 'Bay Horizon - Tower 1 Main Structure',
    project_id: 'prj-2',
    location: 'Seaside Wing, Aseana Park',
    site_supervisor_name: 'Efren Bautista',
    foreman_name: 'Nestor Ramos',
    start_date: '2025-09-15',
    end_date: '2027-08-30',
    status: 'Active'
  },
  {
    id: 'site-4',
    site_code: 'SITE-BAY-02',
    name: 'Bay Horizon - Podium & Deep Foundation',
    project_id: 'prj-2',
    location: 'Central Plaza & Podium Deck, Aseana',
    site_supervisor_name: 'Efren Bautista',
    foreman_name: 'Jose Valenzuela',
    start_date: '2025-10-01',
    end_date: '2026-12-15',
    status: 'Active'
  },
  {
    id: 'site-5',
    site_code: 'SITE-HUB-01',
    name: 'Logistics Hub - Precast Bays & Slab',
    project_id: 'prj-3',
    location: 'Main Logistics Bay 1-4, Cainta',
    site_supervisor_name: 'Fernando Gutierrez',
    foreman_name: 'Rodrigo Morales',
    start_date: '2026-01-10',
    end_date: '2026-11-20',
    status: 'Active'
  }
];

export const initialDocumentCategories = [
  { id: 'cat-1', name: 'Government Identification (SSS/TIN/PhilHealth/ID)', group_type: 'Government' },
  { id: 'cat-2', name: 'Employment Contracts & Offer Letters', group_type: 'Employment' },
  { id: 'cat-3', name: 'DOLE / OSH Safety & Site Induction Pass', group_type: 'Construction / Site' },
  { id: 'cat-4', name: 'TESDA National Competency (NC II / NC III)', group_type: 'Construction / Site' },
  { id: 'cat-5', name: 'Heavy Equipment / Crane Operator License', group_type: 'Construction / Site' },
  { id: 'cat-6', name: 'PRC Professional License & Certifications', group_type: 'Personal' },
  { id: 'cat-7', name: 'Medical Clearance & Drug Test', group_type: 'Personal' },
  { id: 'cat-8', name: 'Barangay & NBI Police Clearance', group_type: 'Personal' }
];

export const initialEmployees = [
  // Office / Professional
  {
    id: 'emp-1',
    employee_id: 'PLN-2026-001',
    first_name: 'Bernardo',
    middle_name: 'Cruz',
    last_name: 'Alcantara',
    suffix: 'Jr.',
    profile_photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&fit=crop&q=80',
    workforce_category: 'office',
    date_of_birth: '1984-05-12',
    gender: 'Male',
    civil_status: 'Married',
    nationality: 'Filipino',
    contact_number: '+63 917 882 1941',
    email: 'b.alcantara@lunayveconstruction.com',
    address: '14 Jade St., San Antonio Village, Pasig City',
    emergency_contact_name: 'Corazon Alcantara',
    emergency_contact_number: '+63 917 554 9012',
    emergency_contact_relation: 'Spouse',
    employment_type: 'Regular',
    employment_status: 'Active',
    department_id: 'dept-4',
    designation_id: 'desig-1',
    date_hired: '2021-03-15',
    contract_start_date: '2021-03-15',
    contract_end_date: null,
    assigned_project_id: 'prj-1',
    assigned_site_id: 'site-1',
    supervisor_id: null,
    foreman_id: null,
    team_crew: 'Project Management Team Alpha',
    date_assigned: '2025-06-01',
    sss_number: '34-8921045-1',
    philhealth_number: '19-029481940-3',
    pagibig_number: '1210-9842-1940',
    tin_number: '284-910-482-000',
    rate_type: 'Monthly',
    base_rate: 95000.00,
    monthly_allowance: 12000.00,
    daily_allowance: 0.00
  },
  {
    id: 'emp-2',
    employee_id: 'PLN-2026-002',
    first_name: 'Maria Elena',
    middle_name: 'Santos',
    last_name: 'Del Rosario',
    suffix: '',
    profile_photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&fit=crop&q=80',
    workforce_category: 'office',
    date_of_birth: '1989-11-24',
    gender: 'Female',
    civil_status: 'Single',
    nationality: 'Filipino',
    contact_number: '+63 920 914 3829',
    email: 'm.delrosario@lunayveconstruction.com',
    address: 'Unit 12B, Pioneer Woodlands Tower 2, Mandaluyong City',
    emergency_contact_name: 'Lourdes Del Rosario',
    emergency_contact_number: '+63 918 293 8471',
    emergency_contact_relation: 'Mother',
    employment_type: 'Regular',
    employment_status: 'Active',
    department_id: 'dept-2',
    designation_id: 'desig-5',
    date_hired: '2022-01-10',
    contract_start_date: '2022-01-10',
    contract_end_date: null,
    assigned_project_id: null,
    assigned_site_id: null,
    supervisor_id: null,
    foreman_id: null,
    team_crew: 'HQ Human Resources',
    date_assigned: '2022-01-10',
    sss_number: '33-7281940-8',
    philhealth_number: '12-984019283-1',
    pagibig_number: '1210-3849-0192',
    tin_number: '394-102-948-000',
    rate_type: 'Monthly',
    base_rate: 75000.00,
    monthly_allowance: 8000.00,
    daily_allowance: 0.00
  },
  {
    id: 'emp-3',
    employee_id: 'PLN-2026-003',
    first_name: 'Christine',
    middle_name: 'Aquino',
    last_name: 'Reyes',
    suffix: '',
    profile_photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&fit=crop&q=80',
    workforce_category: 'office',
    date_of_birth: '1987-08-19',
    gender: 'Female',
    civil_status: 'Married',
    nationality: 'Filipino',
    contact_number: '+63 918 732 1092',
    email: 'c.reyes@lunayveconstruction.com',
    address: '88 Dahlia St., BF Homes, Parañaque City',
    emergency_contact_name: 'Mark Reyes',
    emergency_contact_number: '+63 917 839 2018',
    emergency_contact_relation: 'Spouse',
    employment_type: 'Regular',
    employment_status: 'Active',
    department_id: 'dept-4',
    designation_id: 'desig-4',
    date_hired: '2021-08-01',
    contract_start_date: '2021-08-01',
    contract_end_date: null,
    assigned_project_id: 'prj-2',
    assigned_site_id: 'site-3',
    supervisor_id: null,
    foreman_id: null,
    team_crew: 'Architecture & Design Group',
    date_assigned: '2025-09-15',
    sss_number: '34-1029384-2',
    philhealth_number: '18-293840192-5',
    pagibig_number: '1210-9382-0193',
    tin_number: '482-193-840-000',
    rate_type: 'Monthly',
    base_rate: 88000.00,
    monthly_allowance: 10000.00,
    daily_allowance: 0.00
  },
  {
    id: 'emp-4',
    employee_id: 'PLN-2026-004',
    first_name: 'Daniel',
    middle_name: 'Gabriel',
    last_name: 'Villanueva',
    suffix: '',
    profile_photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&fit=crop&q=80',
    workforce_category: 'office',
    date_of_birth: '1985-02-14',
    gender: 'Male',
    civil_status: 'Married',
    nationality: 'Filipino',
    contact_number: '+63 927 492 0184',
    email: 'd.villanueva@lunayveconstruction.com',
    address: 'Block 5 Lot 12, Valley Golf Subd., Antipolo, Rizal',
    emergency_contact_name: 'Grace Villanueva',
    emergency_contact_number: '+63 917 293 8401',
    emergency_contact_relation: 'Spouse',
    employment_type: 'Regular',
    employment_status: 'Active',
    department_id: 'dept-4',
    designation_id: 'desig-2',
    date_hired: '2020-11-01',
    contract_start_date: '2020-11-01',
    contract_end_date: null,
    assigned_project_id: 'prj-3',
    assigned_site_id: 'site-5',
    supervisor_id: null,
    foreman_id: null,
    team_crew: 'Logistics Engineering Unit',
    date_assigned: '2026-01-10',
    sss_number: '34-2938491-0',
    philhealth_number: '14-293840192-9',
    pagibig_number: '1210-4829-1029',
    tin_number: '592-193-840-000',
    rate_type: 'Monthly',
    base_rate: 82000.00,
    monthly_allowance: 8500.00,
    daily_allowance: 0.00
  },
  {
    id: 'emp-5',
    employee_id: 'PLN-2026-005',
    first_name: 'Patricia',
    middle_name: 'May',
    last_name: 'Lim',
    suffix: 'CPA',
    profile_photo: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=300&fit=crop&q=80',
    workforce_category: 'office',
    date_of_birth: '1992-04-30',
    gender: 'Female',
    civil_status: 'Single',
    nationality: 'Filipino',
    contact_number: '+63 917 382 9104',
    email: 'p.lim@lunayveconstruction.com',
    address: 'Acacia Estates, Taguig City',
    emergency_contact_name: 'Manuel Lim',
    emergency_contact_number: '+63 918 394 0192',
    emergency_contact_relation: 'Father',
    employment_type: 'Regular',
    employment_status: 'Active',
    department_id: 'dept-3',
    designation_id: 'desig-7',
    date_hired: '2023-04-15',
    contract_start_date: '2023-04-15',
    contract_end_date: null,
    assigned_project_id: null,
    assigned_site_id: null,
    supervisor_id: null,
    foreman_id: null,
    team_crew: 'Corporate Payroll & Disbursing',
    date_assigned: '2023-04-15',
    sss_number: '33-9182740-4',
    philhealth_number: '11-829384910-2',
    pagibig_number: '1210-5928-1092',
    tin_number: '482-910-384-000',
    rate_type: 'Monthly',
    base_rate: 62000.00,
    monthly_allowance: 5000.00,
    daily_allowance: 0.00
  },
  {
    id: 'emp-6',
    employee_id: 'PLN-2026-006',
    first_name: 'Engr. Renato',
    middle_name: 'Flores',
    last_name: 'Navarro',
    suffix: '',
    profile_photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&fit=crop&q=80',
    workforce_category: 'office',
    date_of_birth: '1986-07-22',
    gender: 'Male',
    civil_status: 'Married',
    nationality: 'Filipino',
    contact_number: '+63 919 482 9102',
    email: 'r.navarro@lunayveconstruction.com',
    address: 'Kapitolyo, Pasig City',
    emergency_contact_name: 'Theresa Navarro',
    emergency_contact_number: '+63 917 482 1092',
    emergency_contact_relation: 'Spouse',
    employment_type: 'Regular',
    employment_status: 'Active',
    department_id: 'dept-6',
    designation_id: 'desig-9',
    date_hired: '2022-09-01',
    contract_start_date: '2022-09-01',
    contract_end_date: null,
    assigned_project_id: 'prj-1',
    assigned_site_id: 'site-1',
    supervisor_id: 'emp-1',
    foreman_id: null,
    team_crew: 'Central Safety & HSE',
    date_assigned: '2025-06-01',
    sss_number: '34-9182049-5',
    philhealth_number: '15-928401928-4',
    pagibig_number: '1210-9482-1092',
    tin_number: '482-109-384-000',
    rate_type: 'Monthly',
    base_rate: 68000.00,
    monthly_allowance: 6000.00,
    daily_allowance: 0.00
  },

  // Site / Skilled Construction Workers
  {
    id: 'emp-7',
    employee_id: 'PLN-2026-007',
    first_name: 'Rolando',
    middle_name: 'Dela Rosa',
    last_name: 'Mendoza',
    suffix: '',
    profile_photo: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&fit=crop&q=80',
    workforce_category: 'site',
    date_of_birth: '1978-03-10',
    gender: 'Male',
    civil_status: 'Married',
    nationality: 'Filipino',
    contact_number: '+63 928 394 0192',
    email: 'r.mendoza@lunayveconstruction.com',
    address: 'Bgy. Rosario, Pasig City',
    emergency_contact_name: 'Alma Mendoza',
    emergency_contact_number: '+63 920 394 8102',
    emergency_contact_relation: 'Spouse',
    employment_type: 'Regular',
    employment_status: 'Active',
    department_id: 'dept-5',
    designation_id: 'desig-13',
    date_hired: '2019-05-15',
    contract_start_date: '2019-05-15',
    contract_end_date: null,
    assigned_project_id: 'prj-1',
    assigned_site_id: 'site-1',
    supervisor_id: 'emp-1',
    foreman_id: null,
    team_crew: 'Alpha Structural Lead Crew',
    date_assigned: '2025-06-01',
    sss_number: '03-9182740-1',
    philhealth_number: '12-094819283-0',
    pagibig_number: '1210-4820-1928',
    tin_number: '293-849-102-000',
    rate_type: 'Daily',
    base_rate: 1350.00,
    monthly_allowance: 0.00,
    daily_allowance: 200.00
  },
  {
    id: 'emp-8',
    employee_id: 'PLN-2026-008',
    first_name: 'Danilo',
    middle_name: 'Ignacio',
    last_name: 'Cruz',
    suffix: '',
    profile_photo: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=300&fit=crop&q=80',
    workforce_category: 'site',
    date_of_birth: '1981-09-17',
    gender: 'Male',
    civil_status: 'Married',
    nationality: 'Filipino',
    contact_number: '+63 939 482 1093',
    email: 'd.cruz.site@lunayveconstruction.com',
    address: 'Bgy. Pinagbuhatan, Pasig City',
    emergency_contact_name: 'Evelyn Cruz',
    emergency_contact_number: '+63 919 482 0192',
    emergency_contact_relation: 'Spouse',
    employment_type: 'Project-Based',
    employment_status: 'Active',
    department_id: 'dept-5',
    designation_id: 'desig-12',
    date_hired: '2022-03-01',
    contract_start_date: '2025-06-01',
    contract_end_date: '2026-12-31',
    assigned_project_id: 'prj-1',
    assigned_site_id: 'site-1',
    supervisor_id: 'emp-7',
    foreman_id: null,
    team_crew: 'Concrete & Rebar Crew Alpha',
    date_assigned: '2025-06-01',
    sss_number: '03-8291048-2',
    philhealth_number: '14-928401920-1',
    pagibig_number: '1210-9384-0192',
    tin_number: '394-820-192-000',
    rate_type: 'Daily',
    base_rate: 1100.00,
    monthly_allowance: 0.00,
    daily_allowance: 150.00
  },
  {
    id: 'emp-9',
    employee_id: 'PLN-2026-009',
    first_name: 'Juan',
    middle_name: 'Bautista',
    last_name: 'Dela Cruz',
    suffix: '',
    profile_photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&fit=crop&q=80',
    workforce_category: 'site',
    date_of_birth: '1990-06-25',
    gender: 'Male',
    civil_status: 'Married',
    nationality: 'Filipino',
    contact_number: '+63 945 829 1048',
    email: 'j.delacruz.carpenter@lunayveconstruction.com',
    address: 'Sitio Sto. Niño, Taguig City',
    emergency_contact_name: 'Rowena Dela Cruz',
    emergency_contact_number: '+63 928 492 0194',
    emergency_contact_relation: 'Spouse',
    employment_type: 'Project-Based',
    employment_status: 'Active',
    department_id: 'dept-5',
    designation_id: 'desig-15',
    date_hired: '2023-02-15',
    contract_start_date: '2025-06-01',
    contract_end_date: '2026-10-31',
    assigned_project_id: 'prj-1',
    assigned_site_id: 'site-1',
    supervisor_id: 'emp-7',
    foreman_id: 'emp-8',
    team_crew: 'Formwork Carpentry Unit 1',
    date_assigned: '2025-06-01',
    sss_number: '03-7482910-3',
    philhealth_number: '16-928401928-8',
    pagibig_number: '1210-8492-1092',
    tin_number: '482-910-482-000',
    rate_type: 'Daily',
    base_rate: 850.00,
    monthly_allowance: 0.00,
    daily_allowance: 100.00
  },
  {
    id: 'emp-10',
    employee_id: 'PLN-2026-010',
    first_name: 'Nestor',
    middle_name: 'Pascual',
    last_name: 'Ramos',
    suffix: '',
    profile_photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&fit=crop&q=80',
    workforce_category: 'site',
    date_of_birth: '1982-12-04',
    gender: 'Male',
    civil_status: 'Married',
    nationality: 'Filipino',
    contact_number: '+63 916 482 9103',
    email: 'n.ramos.site@lunayveconstruction.com',
    address: 'Bgy. Moonwalk, Parañaque City',
    emergency_contact_name: 'Anita Ramos',
    emergency_contact_number: '+63 917 384 9201',
    emergency_contact_relation: 'Spouse',
    employment_type: 'Regular',
    employment_status: 'Active',
    department_id: 'dept-5',
    designation_id: 'desig-12',
    date_hired: '2021-06-10',
    contract_start_date: '2025-09-15',
    contract_end_date: null,
    assigned_project_id: 'prj-2',
    assigned_site_id: 'site-3',
    supervisor_id: null,
    foreman_id: null,
    team_crew: 'Bay Horizon Superstructure Crew',
    date_assigned: '2025-09-15',
    sss_number: '03-9184029-4',
    philhealth_number: '18-492019482-3',
    pagibig_number: '1210-4829-0193',
    tin_number: '592-109-384-000',
    rate_type: 'Daily',
    base_rate: 1150.00,
    monthly_allowance: 0.00,
    daily_allowance: 150.00
  },
  {
    id: 'emp-11',
    employee_id: 'PLN-2026-011',
    first_name: 'Efren',
    middle_name: 'Tadeo',
    last_name: 'Bautista',
    suffix: '',
    profile_photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&fit=crop&q=80',
    workforce_category: 'site',
    date_of_birth: '1979-04-18',
    gender: 'Male',
    civil_status: 'Married',
    nationality: 'Filipino',
    contact_number: '+63 920 482 1094',
    email: 'e.bautista@lunayveconstruction.com',
    address: 'Bgy. San Dionisio, Parañaque City',
    emergency_contact_name: 'Lilia Bautista',
    emergency_contact_number: '+63 921 482 0193',
    emergency_contact_relation: 'Spouse',
    employment_type: 'Regular',
    employment_status: 'Active',
    department_id: 'dept-5',
    designation_id: 'desig-13',
    date_hired: '2020-04-01',
    contract_start_date: '2020-04-01',
    contract_end_date: null,
    assigned_project_id: 'prj-2',
    assigned_site_id: 'site-3',
    supervisor_id: 'emp-3',
    foreman_id: null,
    team_crew: 'Bay Horizon Lead Supervision',
    date_assigned: '2025-09-15',
    sss_number: '03-1029482-9',
    philhealth_number: '19-482019482-1',
    pagibig_number: '1210-9482-0194',
    tin_number: '394-109-284-000',
    rate_type: 'Daily',
    base_rate: 1400.00,
    monthly_allowance: 0.00,
    daily_allowance: 200.00
  },
  {
    id: 'emp-12',
    employee_id: 'PLN-2026-012',
    first_name: 'Arnel',
    middle_name: 'Villar',
    last_name: 'Soriano',
    suffix: '',
    profile_photo: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=300&fit=crop&q=80',
    workforce_category: 'site',
    date_of_birth: '1988-10-15',
    gender: 'Male',
    civil_status: 'Married',
    nationality: 'Filipino',
    contact_number: '+63 930 482 9104',
    email: 'a.soriano.welder@lunayveconstruction.com',
    address: 'Bgy. San Joaquin, Pasig City',
    emergency_contact_name: 'Marilyn Soriano',
    emergency_contact_number: '+63 928 492 0192',
    emergency_contact_relation: 'Spouse',
    employment_type: 'Project-Based',
    employment_status: 'Active',
    department_id: 'dept-5',
    designation_id: 'desig-21',
    date_hired: '2023-05-10',
    contract_start_date: '2025-06-01',
    contract_end_date: '2026-12-31',
    assigned_project_id: 'prj-1',
    assigned_site_id: 'site-2',
    supervisor_id: 'emp-7',
    foreman_id: 'emp-8',
    team_crew: 'Heavy Structural Welding Unit',
    date_assigned: '2026-02-01',
    sss_number: '03-4920194-5',
    philhealth_number: '17-482910482-9',
    pagibig_number: '1210-3849-1029',
    tin_number: '482-109-482-000',
    rate_type: 'Daily',
    base_rate: 950.00,
    monthly_allowance: 0.00,
    daily_allowance: 120.00
  },
  {
    id: 'emp-13',
    employee_id: 'PLN-2026-013',
    first_name: 'Manuel',
    middle_name: 'Gonzales',
    last_name: 'Castillo',
    suffix: '',
    profile_photo: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&fit=crop&q=80',
    workforce_category: 'site',
    date_of_birth: '1983-01-20',
    gender: 'Male',
    civil_status: 'Married',
    nationality: 'Filipino',
    contact_number: '+63 947 284 9102',
    email: 'm.castillo.operator@lunayveconstruction.com',
    address: 'Bgy. San Andres, Cainta, Rizal',
    emergency_contact_name: 'Gina Castillo',
    emergency_contact_number: '+63 919 482 9104',
    emergency_contact_relation: 'Spouse',
    employment_type: 'Regular',
    employment_status: 'Active',
    department_id: 'dept-5',
    designation_id: 'desig-23',
    date_hired: '2021-01-20',
    contract_start_date: '2025-06-01',
    contract_end_date: null,
    assigned_project_id: 'prj-1',
    assigned_site_id: 'site-2',
    supervisor_id: 'emp-7',
    foreman_id: null,
    team_crew: 'Heavy Lift & Tower Crane Operations',
    date_assigned: '2026-02-01',
    sss_number: '03-8492019-1',
    philhealth_number: '13-482910482-7',
    pagibig_number: '1210-8492-4829',
    tin_number: '592-482-109-000',
    rate_type: 'Daily',
    base_rate: 1300.00,
    monthly_allowance: 0.00,
    daily_allowance: 200.00
  },
  {
    id: 'emp-14',
    employee_id: 'PLN-2026-014',
    first_name: 'Felipe',
    middle_name: 'Santos',
    last_name: 'Macaraeg',
    suffix: '',
    profile_photo: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=300&fit=crop&q=80',
    workforce_category: 'site',
    date_of_birth: '1993-07-08',
    gender: 'Male',
    civil_status: 'Single',
    nationality: 'Filipino',
    contact_number: '+63 915 829 4019',
    email: 'f.macaraeg.mason@lunayveconstruction.com',
    address: 'Bgy. Bagong Ilog, Pasig City',
    emergency_contact_name: 'Pedro Macaraeg',
    emergency_contact_number: '+63 916 482 1092',
    emergency_contact_relation: 'Father',
    employment_type: 'Project-Based',
    employment_status: 'Active',
    department_id: 'dept-5',
    designation_id: 'desig-17',
    date_hired: '2023-08-01',
    contract_start_date: '2025-06-01',
    contract_end_date: '2026-08-31',
    assigned_project_id: 'prj-1',
    assigned_site_id: 'site-1',
    supervisor_id: 'emp-7',
    foreman_id: 'emp-8',
    team_crew: 'Finishing Masonry Crew',
    date_assigned: '2025-06-01',
    sss_number: '03-5928104-6',
    philhealth_number: '14-382910482-6',
    pagibig_number: '1210-9482-1028',
    tin_number: '394-482-109-000',
    rate_type: 'Daily',
    base_rate: 800.00,
    monthly_allowance: 0.00,
    daily_allowance: 100.00
  },
  {
    id: 'emp-15',
    employee_id: 'PLN-2026-015',
    first_name: 'Rico',
    middle_name: 'Dizon',
    last_name: 'Salazar',
    suffix: '',
    profile_photo: 'https://images.unsplash.com/photo-1521119989659-a83eee488004?w=300&fit=crop&q=80',
    workforce_category: 'site',
    date_of_birth: '1995-10-12',
    gender: 'Male',
    civil_status: 'Single',
    nationality: 'Filipino',
    contact_number: '+63 998 482 9104',
    email: 'r.salazar.electrician@lunayveconstruction.com',
    address: 'Bgy. Sto. Domingo, Cainta, Rizal',
    emergency_contact_name: 'Elena Salazar',
    emergency_contact_number: '+63 917 384 9201',
    emergency_contact_relation: 'Mother',
    employment_type: 'Project-Based',
    employment_status: 'Active',
    department_id: 'dept-5',
    designation_id: 'desig-19',
    date_hired: '2024-02-01',
    contract_start_date: '2026-01-10',
    contract_end_date: '2026-11-20',
    assigned_project_id: 'prj-3',
    assigned_site_id: 'site-5',
    supervisor_id: 'emp-4',
    foreman_id: null,
    team_crew: 'Industrial Electrical Bay Crew',
    date_assigned: '2026-01-10',
    sss_number: '03-6928104-9',
    philhealth_number: '12-482910482-4',
    pagibig_number: '1210-4829-9182',
    tin_number: '482-910-582-000',
    rate_type: 'Daily',
    base_rate: 900.00,
    monthly_allowance: 0.00,
    daily_allowance: 120.00
  },
  {
    id: 'emp-16',
    employee_id: 'PLN-2026-016',
    first_name: 'Arturo',
    middle_name: 'Pineda',
    last_name: 'Santos',
    suffix: '',
    profile_photo: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&fit=crop&q=80',
    workforce_category: 'site',
    date_of_birth: '1980-08-30',
    gender: 'Male',
    civil_status: 'Married',
    nationality: 'Filipino',
    contact_number: '+63 922 482 9105',
    email: 'a.santos.foreman@lunayveconstruction.com',
    address: 'Bgy. Buting, Pasig City',
    emergency_contact_name: 'Cecilia Santos',
    emergency_contact_number: '+63 923 482 1093',
    emergency_contact_relation: 'Spouse',
    employment_type: 'Regular',
    employment_status: 'Active',
    department_id: 'dept-5',
    designation_id: 'desig-12',
    date_hired: '2020-02-15',
    contract_start_date: '2026-02-01',
    contract_end_date: null,
    assigned_project_id: 'prj-1',
    assigned_site_id: 'site-2',
    supervisor_id: 'emp-7',
    foreman_id: null,
    team_crew: 'Tower Alpha Superstructure Crew',
    date_assigned: '2026-02-01',
    sss_number: '03-3829104-1',
    philhealth_number: '11-482910482-9',
    pagibig_number: '1210-3849-0182',
    tin_number: '394-109-482-000',
    rate_type: 'Daily',
    base_rate: 1100.00,
    monthly_allowance: 0.00,
    daily_allowance: 150.00
  },
  {
    id: 'emp-17',
    employee_id: 'PLN-2026-017',
    first_name: 'Eduardo',
    middle_name: 'Marquez',
    last_name: 'Tolentino',
    suffix: '',
    profile_photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&fit=crop&q=80',
    workforce_category: 'site',
    date_of_birth: '1991-03-22',
    gender: 'Male',
    civil_status: 'Married',
    nationality: 'Filipino',
    contact_number: '+63 917 849 2018',
    email: 'e.tolentino.steel@lunayveconstruction.com',
    address: 'Bgy. Tambo, Parañaque City',
    emergency_contact_name: 'Gloria Tolentino',
    emergency_contact_number: '+63 918 394 0194',
    emergency_contact_relation: 'Spouse',
    employment_type: 'Project-Based',
    employment_status: 'Active',
    department_id: 'dept-5',
    designation_id: 'desig-22',
    date_hired: '2023-10-01',
    contract_start_date: '2025-09-15',
    contract_end_date: '2026-12-31',
    assigned_project_id: 'prj-2',
    assigned_site_id: 'site-3',
    supervisor_id: 'emp-11',
    foreman_id: 'emp-10',
    team_crew: 'Rebar Steel Fabrication Unit',
    date_assigned: '2025-09-15',
    sss_number: '03-7492019-3',
    philhealth_number: '16-482910482-0',
    pagibig_number: '1210-9482-4820',
    tin_number: '482-394-109-000',
    rate_type: 'Daily',
    base_rate: 850.00,
    monthly_allowance: 0.00,
    daily_allowance: 100.00
  },
  {
    id: 'emp-18',
    employee_id: 'PLN-2026-018',
    first_name: 'Gabriel',
    middle_name: 'Lim',
    last_name: 'Hernandez',
    suffix: '',
    profile_photo: 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?w=300&fit=crop&q=80',
    workforce_category: 'site',
    date_of_birth: '1996-12-05',
    gender: 'Male',
    civil_status: 'Single',
    nationality: 'Filipino',
    contact_number: '+63 927 384 9201',
    email: 'g.hernandez.plumber@lunayveconstruction.com',
    address: 'Bgy. San Isidro, Cainta, Rizal',
    emergency_contact_name: 'Rosa Hernandez',
    emergency_contact_number: '+63 928 482 1094',
    emergency_contact_relation: 'Mother',
    employment_type: 'Project-Based',
    employment_status: 'Active',
    department_id: 'dept-5',
    designation_id: 'desig-20',
    date_hired: '2024-03-01',
    contract_start_date: '2026-01-10',
    contract_end_date: '2026-11-20',
    assigned_project_id: 'prj-3',
    assigned_site_id: 'site-5',
    supervisor_id: 'emp-4',
    foreman_id: null,
    team_crew: 'Piping & Sanitary Unit',
    date_assigned: '2026-01-10',
    sss_number: '03-8492019-7',
    philhealth_number: '14-482910482-5',
    pagibig_number: '1210-3849-4829',
    tin_number: '592-394-109-000',
    rate_type: 'Daily',
    base_rate: 880.00,
    monthly_allowance: 0.00,
    daily_allowance: 100.00
  },
  {
    id: 'emp-19',
    employee_id: 'PLN-2026-019',
    first_name: 'Rodrigo',
    middle_name: 'Castillo',
    last_name: 'Morales',
    suffix: '',
    profile_photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&fit=crop&q=80',
    workforce_category: 'site',
    date_of_birth: '1984-04-14',
    gender: 'Male',
    civil_status: 'Married',
    nationality: 'Filipino',
    contact_number: '+63 919 384 9201',
    email: 'r.morales.foreman@lunayveconstruction.com',
    address: 'Bgy. San Roque, Cainta, Rizal',
    emergency_contact_name: 'Juana Morales',
    emergency_contact_number: '+63 920 482 1095',
    emergency_contact_relation: 'Spouse',
    employment_type: 'Regular',
    employment_status: 'Active',
    department_id: 'dept-5',
    designation_id: 'desig-12',
    date_hired: '2021-08-15',
    contract_start_date: '2026-01-10',
    contract_end_date: null,
    assigned_project_id: 'prj-3',
    assigned_site_id: 'site-5',
    supervisor_id: 'emp-4',
    foreman_id: null,
    team_crew: 'Logistics Hub Civil Works',
    date_assigned: '2026-01-10',
    sss_number: '03-9482019-2',
    philhealth_number: '15-482910482-2',
    pagibig_number: '1210-9482-3849',
    tin_number: '482-109-592-000',
    rate_type: 'Daily',
    base_rate: 1100.00,
    monthly_allowance: 0.00,
    daily_allowance: 150.00
  },
  {
    id: 'emp-20',
    employee_id: 'PLN-2026-020',
    first_name: 'Benjamin',
    middle_name: 'Torres',
    last_name: 'Abad',
    suffix: '',
    profile_photo: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=300&fit=crop&q=80',
    workforce_category: 'site',
    date_of_birth: '1998-01-28',
    gender: 'Male',
    civil_status: 'Single',
    nationality: 'Filipino',
    contact_number: '+63 933 482 9104',
    email: 'b.abad.labor@lunayveconstruction.com',
    address: 'Bgy. Rosario, Pasig City',
    emergency_contact_name: 'Simeon Abad',
    emergency_contact_number: '+63 934 482 1093',
    emergency_contact_relation: 'Father',
    employment_type: 'Project-Based',
    employment_status: 'Active',
    department_id: 'dept-5',
    designation_id: 'desig-27',
    date_hired: '2025-06-01',
    contract_start_date: '2025-06-01',
    contract_end_date: '2026-09-30',
    assigned_project_id: 'prj-1',
    assigned_site_id: 'site-1',
    supervisor_id: 'emp-7',
    foreman_id: 'emp-8',
    team_crew: 'General Site Clearing & Support',
    date_assigned: '2025-06-01',
    sss_number: '03-8492019-4',
    philhealth_number: '12-482910482-8',
    pagibig_number: '1210-4829-3849',
    tin_number: '394-592-109-000',
    rate_type: 'Daily',
    base_rate: 650.00,
    monthly_allowance: 0.00,
    daily_allowance: 80.00
  }
];

export const initialSiteAssignments = [
  {
    id: 'asg-1',
    employee_id: 'emp-9',
    project_id: 'prj-1',
    site_id: 'site-1',
    position_title: 'Formwork Carpenter',
    supervisor_name: 'Rolando Mendoza',
    assignment_start: '2025-06-01',
    assignment_end: null,
    status: 'Active',
    notes: 'Assigned to Basement Mat Foundation formwork staging'
  },
  {
    id: 'asg-2',
    employee_id: 'emp-9',
    project_id: 'prj-3',
    site_id: 'site-5',
    position_title: 'Assistant Formwork Carpenter',
    supervisor_name: 'Fernando Gutierrez',
    assignment_start: '2024-03-01',
    assignment_end: '2025-05-20',
    status: 'Completed',
    notes: 'Completed warehouse pre-cast formwork setup'
  },
  {
    id: 'asg-3',
    employee_id: 'emp-12',
    project_id: 'prj-1',
    site_id: 'site-2',
    position_title: 'SMAW/GTAW Certified Welder',
    supervisor_name: 'Rolando Mendoza',
    assignment_start: '2026-02-01',
    assignment_end: null,
    status: 'Active',
    notes: 'Tower crane anchor beam welding & core moment connections'
  },
  {
    id: 'asg-4',
    employee_id: 'emp-12',
    project_id: 'prj-1',
    site_id: 'site-1',
    position_title: 'Structural Welder',
    supervisor_name: 'Rolando Mendoza',
    assignment_start: '2025-06-01',
    assignment_end: '2026-01-31',
    status: 'Transferred',
    notes: 'Transferred from basement pile cap welding to high rise core'
  }
];

export const initialDocuments = [
  {
    id: 'doc-1',
    employee_id: 'emp-9',
    category_id: 'cat-3',
    document_name: 'DOLE BOSH / COSH Safety Induction Certificate',
    file_name: 'BOSH_Juan_DelaCruz_2025.pdf',
    file_path: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&fit=crop&q=80',
    file_type: 'application/pdf',
    file_size: 1428500,
    expiration_date: '2026-09-15', // Expiring soon!
    uploaded_by: 'emp-2',
    uploader_name: 'Maria Elena Del Rosario',
    notes: '40-Hour Construction Safety and Health DOLE accredited certificate'
  },
  {
    id: 'doc-2',
    employee_id: 'emp-9',
    category_id: 'cat-4',
    document_name: 'TESDA NC II - Carpentry Certification',
    file_name: 'TESDA_NCII_Carpentry_Juan.pdf',
    file_path: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&fit=crop&q=80',
    file_type: 'application/pdf',
    file_size: 980200,
    expiration_date: '2028-11-20',
    uploaded_by: 'emp-2',
    uploader_name: 'Maria Elena Del Rosario',
    notes: 'Verified against TESDA online registry'
  },
  {
    id: 'doc-3',
    employee_id: 'emp-13',
    category_id: 'cat-5',
    document_name: 'Heavy Equipment Operator License - Tower Crane Level 3',
    file_name: 'Crane_License_ManuelCastillo.jpg',
    file_path: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&fit=crop&q=80',
    file_type: 'image/jpeg',
    file_size: 2100400,
    expiration_date: '2026-04-10', // Expired / Urgent
    uploaded_by: 'emp-2',
    uploader_name: 'Maria Elena Del Rosario',
    notes: 'Urgent renewal required for Tower Crane Alpha'
  },
  {
    id: 'doc-4',
    employee_id: 'emp-1',
    category_id: 'cat-6',
    document_name: 'PRC Professional Civil Engineer License',
    file_name: 'PRC_License_EngrAlcantara.pdf',
    file_path: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&fit=crop&q=80',
    file_type: 'application/pdf',
    file_size: 1840200,
    expiration_date: '2027-05-12',
    uploaded_by: 'emp-2',
    uploader_name: 'Maria Elena Del Rosario',
    notes: 'Active PRC Member in good standing'
  }
];

export const initialLeaveTypes = [
  { id: 'leave-1', code: 'VL', name: 'Vacation Leave', days_allowed_per_year: 15, is_paid: true },
  { id: 'leave-2', code: 'SL', name: 'Sick Leave', days_allowed_per_year: 15, is_paid: true },
  { id: 'leave-3', code: 'EL', name: 'Emergency / Calamity Leave', days_allowed_per_year: 5, is_paid: true },
  { id: 'leave-4', code: 'SPL', name: 'Solo Parent Leave', days_allowed_per_year: 7, is_paid: true },
  { id: 'leave-5', code: 'ML', name: 'Maternity Leave', days_allowed_per_year: 105, is_paid: true },
  { id: 'leave-6', code: 'PL', name: 'Paternity Leave', days_allowed_per_year: 7, is_paid: true }
];

export const initialLeaveRequests = [
  {
    id: 'lvr-1',
    employee_id: 'emp-9',
    leave_type_id: 'leave-1',
    start_date: '2026-09-01',
    end_date: '2026-09-03',
    total_days: 3,
    reason: 'Family province visit in Batangas for fiesta',
    status: 'Approved',
    approved_by: 'emp-2',
    approver_name: 'Maria Elena Del Rosario',
    approval_date: '2026-08-25',
    rejection_reason: null
  },
  {
    id: 'lvr-2',
    employee_id: 'emp-15',
    leave_type_id: 'leave-2',
    start_date: '2026-08-28',
    end_date: '2026-08-29',
    total_days: 2,
    reason: 'Severe flu symptoms and medical checkup',
    status: 'Pending',
    approved_by: null,
    approver_name: null,
    approval_date: null,
    rejection_reason: null
  }
];

export const initialGovernmentRules = [
  {
    id: 'gov-1',
    agency: 'SSS',
    rule_name: 'SSS Standard Contribution Table 2026 (14% Rate)',
    effective_date: '2026-01-01',
    min_base: 5000.00,
    max_base: 35000.00,
    employee_share_pct: 0.045, // 4.5%
    employer_share_pct: 0.095, // 9.5%
    employee_fixed_amount: 0,
    employer_fixed_amount: 30.00, // EC fund
    is_active: true
  },
  {
    id: 'gov-2',
    agency: 'PhilHealth',
    rule_name: 'PhilHealth Premium 2026 (5.0% Equal Share)',
    effective_date: '2026-01-01',
    min_base: 10000.00,
    max_base: 100000.00,
    employee_share_pct: 0.025, // 2.5%
    employer_share_pct: 0.025, // 2.5%
    employee_fixed_amount: 0,
    employer_fixed_amount: 0,
    is_active: true
  },
  {
    id: 'gov-3',
    agency: 'Pag-IBIG',
    rule_name: 'Pag-IBIG Mandatory Contribution 2026 (₱200 Cap)',
    effective_date: '2026-01-01',
    min_base: 1500.00,
    max_base: 10000.00,
    employee_share_pct: 0.02,
    employer_share_pct: 0.02,
    employee_fixed_amount: 200.00,
    employer_fixed_amount: 200.00,
    is_active: true
  },
  {
    id: 'gov-4',
    agency: 'BIR_Tax',
    rule_name: 'BIR TRAIN Law Withholding Tax Brackets (Semi-Monthly)',
    effective_date: '2026-01-01',
    min_base: 10417.00,
    max_base: 33333.00,
    tax_base_offset: 10417.00,
    tax_excess_pct: 0.15,
    is_active: true
  }
];

export const initialPayrollPeriods = [
  {
    id: 'pr-1',
    period_code: 'PR-2026-08A',
    period_type: 'Semi-Monthly',
    start_date: '2026-08-01',
    end_date: '2026-08-15',
    payout_date: '2026-08-20',
    status: 'Approved',
    total_gross: 485200.00,
    total_deductions: 54100.00,
    total_net: 431100.00,
    approved_by: 'emp-2',
    approver_name: 'Maria Elena Del Rosario',
    approved_at: '2026-08-18T14:30:00Z',
    notes: 'First half of August 2026 regular payroll'
  },
  {
    id: 'pr-2',
    period_code: 'PR-2026-08B',
    period_type: 'Semi-Monthly',
    start_date: '2026-08-16',
    end_date: '2026-08-31',
    payout_date: '2026-09-05',
    status: 'For Review',
    total_gross: 512400.00,
    total_deductions: 58200.00,
    total_net: 454200.00,
    approved_by: null,
    approver_name: null,
    approved_at: null,
    notes: 'Second half August 2026 payroll including site overtime & holiday pays'
  }
];

export const initialAuditLogs = [
  {
    id: 'aud-1',
    user_name: 'Maria Elena Del Rosario',
    user_role: 'HR Administrator',
    action: 'Approved Payroll Period PR-2026-08A',
    module: 'Payroll',
    record_id: 'pr-1',
    details: { total_net: 431100.00, count: 20 },
    created_at: '2026-08-18T14:30:00Z'
  },
  {
    id: 'aud-2',
    user_name: 'Maria Elena Del Rosario',
    user_role: 'HR Administrator',
    action: 'Assigned Juan Dela Cruz to Tower Alpha - Substructure',
    module: 'Sites',
    record_id: 'emp-9',
    details: { project: 'Lunayve Tower Alpha', site: 'SITE-ALPHA-01' },
    created_at: '2026-08-15T09:20:00Z'
  },
  {
    id: 'aud-3',
    user_name: 'Patricia Lim',
    user_role: 'Payroll Administrator',
    action: 'Generated Draft Payroll PR-2026-08B',
    module: 'Payroll',
    record_id: 'pr-2',
    details: { period: '2026-08-16 to 2026-08-31' },
    created_at: '2026-08-26T16:45:00Z'
  },
  {
    id: 'aud-4',
    user_name: 'Maria Elena Del Rosario',
    user_role: 'HR Administrator',
    action: 'Uploaded Document BOSH_Juan_DelaCruz_2025.pdf',
    module: 'Documents',
    record_id: 'doc-1',
    details: { category: 'DOLE / OSH Safety Pass' },
    created_at: '2026-08-20T11:15:00Z'
  }
];

export const initialNotifications = [
  {
    id: 'notif-1',
    title: 'Document Expired: Heavy Crane Operator License',
    message: 'Manuel Castillo\'s Tower Crane Operator License expired on April 10, 2026.',
    type: 'expired_doc',
    link: '/employees/emp-13',
    is_read: false,
    created_at: '2026-08-27T08:00:00Z'
  },
  {
    id: 'notif-2',
    title: 'Document Expiring Soon: DOLE Safety Pass',
    message: 'Juan Dela Cruz\'s DOLE BOSH Certificate will expire on Sept 15, 2026.',
    type: 'expiring_doc',
    link: '/employees/emp-9',
    is_read: false,
    created_at: '2026-08-26T10:00:00Z'
  },
  {
    id: 'notif-3',
    title: 'Payroll Awaiting Approval',
    message: 'Period PR-2026-08B (₱454,200.00 Net) is waiting for Super Admin approval.',
    type: 'payroll_pending',
    link: '/payroll',
    is_read: false,
    created_at: '2026-08-27T09:30:00Z'
  },
  {
    id: 'notif-4',
    title: 'Pending Leave Request',
    message: 'Rico Salazar has applied for 2 days Sick Leave.',
    type: 'leave_pending',
    link: '/leave',
    is_read: false,
    created_at: '2026-08-27T11:00:00Z'
  }
];
